import { Layout } from "@/components/Layout";
import { ScrollReveal } from "@/hooks/use-scroll-reveal";
import { Link } from "react-router-dom";
import { ArrowRight, FileText, CheckCircle, AlertTriangle, CreditCard, Scale, Zap, RefreshCw, MessageSquare, Gavel } from "lucide-react";
import { motion } from "framer-motion";

const Terms = () => {
  const sections = [
    {
      icon: CheckCircle,
      title: "Acceptance of Terms",
      content: `By downloading, accessing, or using the Bubly application ("App" or "Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, please do not use the Service.

These Terms constitute a legally binding agreement between you and Bubly ("we," "us," or "our"). We may update these Terms from time to time, and your continued use of the Service after any changes constitutes acceptance of the new Terms.`
    },
    {
      icon: Zap,
      title: "Service Description",
      description: "Bubly is an intelligent social relationship management app designed to help you nurture meaningful connections. Our Service includes:",
      items: [
        "Contact management with custom categorization and notes",
        "Smart reminders for birthdays, anniversaries, and important dates",
        "AI-powered greeting message suggestions",
        "Interaction history and relationship insights",
        "iCloud sync for seamless multi-device access (optional)",
      ]
    },
    {
      icon: FileText,
      title: "User Accounts & Eligibility",
      subsections: [
        {
          subtitle: "Eligibility",
          content: "You must be at least 13 years old (or the minimum age of digital consent in your jurisdiction) to use this Service. By using Bubly, you represent that you meet this requirement."
        },
        {
          subtitle: "Account Responsibility",
          content: "You are responsible for maintaining the confidentiality of your device and any data stored within the App. You agree to accept responsibility for all activities that occur under your account or device."
        },
      ]
    },
    {
      icon: AlertTriangle,
      title: "Acceptable Use Policy",
      description: "You agree to use the Service only for lawful purposes. You shall not:",
      items: [
        "Use the Service to harass, abuse, or harm another person",
        "Send spam, phishing, or other unsolicited communications using content generated by our AI",
        "Attempt to gain unauthorized access to the Service or its related systems",
        "Reverse engineer, decompile, or disassemble any part of the Service",
        "Use the Service to infringe on intellectual property rights of others",
        "Use automated scripts or bots to access the Service",
        "Violate any applicable laws or regulations",
      ]
    },
    {
      icon: Scale,
      title: "Intellectual Property",
      subsections: [
        {
          subtitle: "Our Rights",
          content: "The Service, including its software, design, logos, trademarks, and all content, is owned by Bubly and protected by intellectual property laws. You may not copy, modify, distribute, or create derivative works without our express permission."
        },
        {
          subtitle: "Your Content",
          content: "You retain ownership of any data you create within the App. By using AI features, you grant us a limited license to process your inputs solely to generate responses. We do not store or use your inputs for any other purpose."
        },
        {
          subtitle: "AI-Generated Content",
          content: "Greeting messages generated by our AI are provided for your personal use. You may freely use, modify, and share these messages. However, you may not claim such content was created by a different AI service or use it for commercial purposes without our consent."
        },
      ]
    },
    {
      icon: CreditCard,
      title: "Subscriptions & Payments",
      subsections: [
        {
          subtitle: "Free & Premium Tiers",
          list: [
            { label: "Free", desc: "Basic features including contact management and limited AI generations" },
            { label: "Premium", desc: "Unlimited AI generations, advanced analytics, priority support, and exclusive features" },
          ]
        },
        {
          subtitle: "Billing",
          content: "Subscription fees are billed through your Apple ID account. Prices are displayed in your local currency and may include applicable taxes."
        },
        {
          subtitle: "Auto-Renewal",
          content: "Subscriptions automatically renew unless you cancel at least 24 hours before the end of the current billing period. You can manage or cancel your subscription in your device's App Store settings."
        },
        {
          subtitle: "Refunds",
          content: "All purchases are processed by Apple and are subject to Apple's refund policies. We do not have the ability to issue refunds directly."
        },
      ]
    },
    {
      icon: RefreshCw,
      title: "Service Availability & Changes",
      content: `We strive to provide a reliable Service, but do not guarantee uninterrupted availability. We may:

• Modify, suspend, or discontinue features without prior notice
• Perform maintenance that may temporarily affect Service availability
• Update the App to improve functionality or security

We will make reasonable efforts to notify you of significant changes that may affect your use of the Service.`
    },
    {
      icon: AlertTriangle,
      title: "Disclaimers",
      isWarning: true,
      content: `THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO:

• Implied warranties of merchantability or fitness for a particular purpose
• Warranties that the Service will be uninterrupted, secure, or error-free
• Warranties regarding the accuracy or reliability of AI-generated content

You acknowledge that AI-generated messages are suggestions only and may not be appropriate for all situations. You are solely responsible for reviewing and modifying content before use.`
    },
    {
      icon: Scale,
      title: "Limitation of Liability",
      content: `TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, BUBLY AND ITS AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE FOR:

• Any indirect, incidental, special, consequential, or punitive damages
• Loss of data, profits, goodwill, or other intangible losses
• Damages arising from your use or inability to use the Service
• Damages arising from unauthorized access to your data

Our total liability shall not exceed the amount you paid for the Service in the twelve (12) months preceding the claim.`
    },
    {
      icon: MessageSquare,
      title: "Dispute Resolution",
      subsections: [
        {
          subtitle: "Informal Resolution",
          content: "Before filing any formal dispute, you agree to first contact us to attempt to resolve the issue informally. Most concerns can be resolved quickly through our support team."
        },
        {
          subtitle: "Governing Law",
          content: "These Terms shall be governed by and construed in accordance with applicable laws, without regard to conflict of law principles."
        },
      ]
    },
    {
      icon: Gavel,
      title: "General Provisions",
      items: [
        { label: "Entire Agreement", desc: "These Terms constitute the entire agreement between you and Bubly regarding the Service" },
        { label: "Severability", desc: "If any provision is found unenforceable, the remaining provisions will continue in effect" },
        { label: "Waiver", desc: "Our failure to enforce any right does not constitute a waiver of that right" },
        { label: "Assignment", desc: "You may not assign these Terms without our consent; we may assign them freely" },
      ]
    },
  ];

  return (
    <Layout>
      {/* Hero Section */}
      <section className="relative py-16 md:py-28 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-b from-bubly-pink/5 via-transparent to-transparent pointer-events-none" />
        <motion.div
          className="absolute top-1/3 left-1/4 w-[300px] md:w-[500px] h-[300px] md:h-[500px] bg-bubly-pink/10 rounded-full blur-[100px] pointer-events-none"
          animate={{ scale: [1, 1.1, 1], opacity: [0.3, 0.5, 0.3] }}
          transition={{ duration: 8, repeat: Infinity }}
        />

        <div className="container mx-auto px-4 relative z-10">
          <ScrollReveal className="text-center max-w-3xl mx-auto">
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full glass text-xs font-medium text-muted-foreground mb-6 tracking-wide uppercase">
              <FileText className="w-4 h-4" />
              Legal Agreement
            </div>
            <h1 className="text-3xl md:text-5xl lg:text-6xl font-bold mb-6">
              Terms of <span className="gradient-text">Service</span>
            </h1>
            <p className="text-base md:text-lg text-muted-foreground mb-4">
              The rules and guidelines for using Bubly responsibly.
            </p>
            <p className="text-sm text-muted-foreground/70">
              Effective Date: December 26, 2025 • Version 1.0
            </p>
          </ScrollReveal>
        </div>
      </section>

      {/* Quick Summary Banner */}
      <section className="py-8">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            <div className="p-6 md:p-8 rounded-2xl bg-gradient-to-r from-blue-500/10 via-indigo-500/10 to-violet-500/10 border border-blue-500/20">
              <div className="flex items-start gap-4">
                <div className="w-12 h-12 rounded-xl bg-blue-500/20 flex items-center justify-center flex-shrink-0">
                  <CheckCircle className="w-6 h-6 text-blue-400" />
                </div>
                <div>
                  <h3 className="text-lg font-bold text-foreground mb-2">📋 The Short Version</h3>
                  <ul className="space-y-1 text-sm text-muted-foreground">
                    <li>✓ Use Bubly to nurture genuine relationships, not to spam</li>
                    <li>✓ Your data belongs to you — we just help you manage it</li>
                    <li>✓ AI suggestions are helpful hints, not guaranteed perfection</li>
                    <li>✓ Be a good human — don't do illegal stuff with our app</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Main Content */}
      <section className="py-8 md:py-16 overflow-hidden">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto space-y-8 md:space-y-12">
            {sections.map((section, idx) => (
              <ScrollReveal key={idx}>
                <div className={`p-6 md:p-8 rounded-2xl border ${section.isWarning ? 'border-amber-500/30 bg-amber-500/5' : 'border-white/10 bg-white/[0.02]'} backdrop-blur-sm hover:border-white/20 transition-colors`}>
                  <div className="flex items-start gap-4 mb-6">
                    <div className={`w-10 h-10 md:w-12 md:h-12 rounded-xl ${section.isWarning ? 'bg-amber-500/20' : 'bg-gradient-bubly'} flex items-center justify-center flex-shrink-0`}>
                      <section.icon className={`w-5 h-5 md:w-6 md:h-6 ${section.isWarning ? 'text-amber-400' : 'text-white'}`} />
                    </div>
                    <div>
                      <span className="text-xs text-muted-foreground/60 uppercase tracking-widest">Section {idx + 1}</span>
                      <h2 className="text-xl md:text-2xl font-bold text-foreground">{section.title}</h2>
                    </div>
                  </div>

                  <div className="pl-0 md:pl-16 space-y-4">
                    {section.description && (
                      <p className="text-sm md:text-base text-foreground/80 leading-relaxed">
                        {section.description}
                      </p>
                    )}

                    {section.content && typeof section.content === 'string' && (
                      <p className="text-sm md:text-base text-foreground/80 leading-relaxed whitespace-pre-line">
                        {section.content}
                      </p>
                    )}

                    {section.items && (
                      <ul className="space-y-2">
                        {section.items.map((item, i) => (
                          <li key={i} className="flex items-start gap-3 text-sm text-foreground/70">
                            <span className="w-1.5 h-1.5 rounded-full bg-bubly-pink mt-1.5 flex-shrink-0" />
                            {typeof item === 'string' ? item : (
                              <span><strong className="text-foreground">{item.label}:</strong> {item.desc}</span>
                            )}
                          </li>
                        ))}
                      </ul>
                    )}

                    {section.subsections?.map((sub, i) => (
                      <div key={i} className="space-y-2">
                        <h4 className="text-sm font-semibold text-foreground">{sub.subtitle}</h4>
                        {sub.content && (
                          <p className="text-sm text-foreground/70 leading-relaxed">{sub.content}</p>
                        )}
                        {sub.list && (
                          <ul className="space-y-2">
                            {sub.list.map((listItem, j) => (
                              <li key={j} className="flex items-start gap-3 text-sm text-foreground/70">
                                <span className="w-1.5 h-1.5 rounded-full bg-bubly-pink mt-1.5 flex-shrink-0" />
                                <span><strong className="text-foreground">{listItem.label}:</strong> {listItem.desc}</span>
                              </li>
                            ))}
                          </ul>
                        )}
                      </div>
                    ))}
                  </div>
                </div>
              </ScrollReveal>
            ))}

            {/* Contact Section */}
            <ScrollReveal>
              <div className="p-6 md:p-8 rounded-2xl border border-bubly-pink/30 bg-bubly-pink/5">
                <div className="flex items-start gap-4">
                  <div className="w-10 h-10 md:w-12 md:h-12 rounded-xl bg-bubly-pink/20 flex items-center justify-center flex-shrink-0">
                    <MessageSquare className="w-5 h-5 md:w-6 md:h-6 text-bubly-pink" />
                  </div>
                  <div>
                    <h3 className="text-lg font-bold text-foreground mb-2">Questions About These Terms?</h3>
                    <p className="text-sm text-foreground/70 mb-4">
                      We're happy to clarify anything. Reach out to our team and we'll get back to you promptly.
                    </p>
                    <Link
                      to="/contact"
                      className="inline-flex items-center gap-2 text-sm font-medium text-bubly-pink hover:underline"
                    >
                      Contact Us <ArrowRight className="w-4 h-4" />
                    </Link>
                  </div>
                </div>
              </div>
            </ScrollReveal>
          </div>
        </div>
      </section>

      {/* Related Links */}
      <section className="py-12 md:py-16">
        <div className="container mx-auto px-4">
          <ScrollReveal className="max-w-4xl mx-auto">
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link
                to="/privacy"
                className="group inline-flex items-center justify-center gap-2 px-6 py-3 rounded-full bg-white/5 border border-white/10 hover:bg-white/10 hover:border-white/20 transition-all duration-300"
              >
                Privacy Policy
                <ArrowRight className="w-4 h-4 transition-transform duration-300 group-hover:translate-x-1" />
              </Link>
              <Link
                to="/contact"
                className="group inline-flex items-center justify-center gap-2 px-6 py-3 rounded-full bg-white/5 border border-white/10 hover:bg-white/10 hover:border-white/20 transition-all duration-300"
              >
                Contact Us
                <ArrowRight className="w-4 h-4 transition-transform duration-300 group-hover:translate-x-1" />
              </Link>
            </div>
          </ScrollReveal>
        </div>
      </section>
    </Layout>
  );
};

export default Terms;
